# Generated by Django 5.1.7 on 2025-04-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название статьи"),
                ),
                ("article_text", models.TextField(verbose_name="Текст статьи")),
                ("reading_time", models.IntegerField(verbose_name="Время чтения")),
                ("date_published", models.DateField(verbose_name="Дата публикации")),
                ("image", models.FileField(upload_to="")),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название продукта"
                    ),
                ),
                (
                    "image",
                    models.FileField(upload_to="", verbose_name="Картинка бренда"),
                ),
            ],
            options={
                "verbose_name": "Брэнд",
                "verbose_name_plural": "Брэнды",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Категория продукта"
                    ),
                ),
                (
                    "image",
                    models.FileField(upload_to="", verbose_name="Картинка категории"),
                ),
            ],
            options={
                "verbose_name": "Категория товара",
                "verbose_name_plural": "Категория товаров",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название акции"),
                ),
                ("text", models.TextField(verbose_name="Текст акции")),
                (
                    "image",
                    models.ImageField(upload_to="", verbose_name="Картинка акции"),
                ),
                ("start_date", models.DateTimeField(verbose_name="Начало акции")),
                ("end_date", models.DateTimeField(verbose_name="Конец акции")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Кол-во продукта")),
                (
                    "unit",
                    models.CharField(
                        choices=[("кг", "кг"), ("л", "л"), ("г", "г"), ("шт", "шт")],
                        max_length=255,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        null=True, verbose_name="Дата добавления продукта"
                    ),
                ),
                (
                    "popularity",
                    models.IntegerField(
                        default=0, verbose_name="Популярность продукта"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "product_category",
                    models.ManyToManyField(
                        to="catalog.productcategory", verbose_name="Категория продукта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="FavouriteProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.userprofile",
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="brand",
            name="product_category",
            field=models.ManyToManyField(
                to="catalog.productcategory", verbose_name="Категория продукта"
            ),
        ),
        migrations.CreateModel(
            name="ProductDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "key_features",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ключевые особенности"
                    ),
                ),
                (
                    "ingridients",
                    models.TextField(blank=True, null=True, verbose_name="Состав"),
                ),
                (
                    "guaranteed_analysis",
                    models.TextField(
                        blank=True, null=True, verbose_name="Гарантированный анализ"
                    ),
                ),
                (
                    "food_additives",
                    models.TextField(
                        blank=True, null=True, verbose_name="Пищевые добавки"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Описание продукта",
                "verbose_name_plural": "Описание продуктов",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(upload_to="", verbose_name="Картинка продукта"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка продукта",
                "verbose_name_plural": "Картинки продуктов",
            },
        ),
        migrations.CreateModel(
            name="ProductProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Вес"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расфасовка продукта",
                "verbose_name_plural": "Расфасовка продуктов",
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Тип продукта")),
                (
                    "product_category",
                    models.ManyToManyField(
                        to="catalog.productcategory", verbose_name="Категория продукта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип продукта",
                "verbose_name_plural": "Типы продуктов",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="catalog.producttype",
                verbose_name="Тип продукта",
            ),
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Цена со скидкой"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Дата начала акции")),
                ("end_date", models.DateTimeField(verbose_name="Дата окончания акции")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акционный товар",
                "verbose_name_plural": "Акционные товары",
            },
        ),
    ]
