# Generated by Django 5.1.3 on 2024-12-02 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Картинка продукта', 'verbose_name_plural': 'Картинки продуктов'},
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_features', models.TextField(null=True, verbose_name='Ключевые особенности')),
                ('ingridients', models.TextField(null=True, verbose_name='Состав')),
                ('guaranteed_analysis', models.TextField(null=True, verbose_name='Гарантированный анализ')),
                ('food_additives', models.TextField(null=True, verbose_name='Пищевые добавки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Описание продукта',
                'verbose_name_plural': 'Описание продуктов',
            },
        ),
    ]
