# Generated by Django 5.1.3 on 2025-01-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_producttype_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='productCategory',
            field=models.ManyToManyField(to='catalog.productcategory', verbose_name='Категория продукта'),
        ),
    ]
