# Generated by Django 5.1.3 on 2024-12-15 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_type_of_product_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='product_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='catalog.producttype'),
        ),
    ]
