# Generated by Django 5.1.3 on 2024-12-15 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_brand_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='product_type',
        ),
        migrations.AddField(
            model_name='brand',
            name='product_category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='catalog.productcategory'),
        ),
    ]
