# Generated by Django 5.1.3 on 2025-01-02 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_productcategory_producttype_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.producttype', verbose_name='Тип продукта'),
            preserve_default=False,
        ),
    ]
