# Generated by Django 5.1.3 on 2024-12-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.FileField(default='cat.png', upload_to='', verbose_name='Картинка бренда'),
            preserve_default=False,
        ),
    ]
