# Generated by Django 5.1.3 on 2024-12-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_product_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='product_category',
        ),
        migrations.AddField(
            model_name='brand',
            name='product_category',
            field=models.ManyToManyField(to='catalog.productcategory'),
        ),
    ]
