# Generated by Django 5.1.3 on 2024-12-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='Популярность продукта'),
        ),
    ]
