# Generated by Django 5.1.3 on 2024-12-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperties',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена'),
        ),
    ]
