# Generated by Django 5.1.3 on 2025-01-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_article_options_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название статьи"),
        ),
    ]
