# Generated by Django 5.1.3 on 2025-02-16 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0016_delete_cartitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_num", models.CharField(verbose_name="Номер заказа")),
                ("receipt", models.FileField(upload_to="receipts", verbose_name="Чек")),
                (
                    "order_sum",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма заказа"
                    ),
                ),
                (
                    "payment_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Наличными при получении"), (2, "Картой")],
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Оформлен"),
                            (2, "Ожидает оплату"),
                            (3, "Оплачен"),
                            (4, "Подтвержден"),
                            (5, "Выполнен"),
                            (6, "Аннулирован"),
                            (7, "Ошибка оплаты"),
                        ],
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "show_order_to_user",
                    models.BooleanField(verbose_name="Показывать заказ пользователю"),
                ),
                (
                    "delivery_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Самовывоз"), (2, "Доставка курьером")],
                        verbose_name="Способ получения товара",
                    ),
                ),
                ("city", models.CharField(blank=True, null=True, verbose_name="Город")),
                (
                    "street",
                    models.CharField(
                        blank=True, null=True, verbose_name="Улица/Переулок"
                    ),
                ),
                (
                    "house_num",
                    models.CharField(blank=True, null=True, verbose_name="Номер дома"),
                ),
                (
                    "entrance_num",
                    models.CharField(
                        blank=True, null=True, verbose_name="Номер подъезда"
                    ),
                ),
                (
                    "apartment_num",
                    models.CharField(
                        blank=True, null=True, verbose_name="Номер квартиры"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, null=True, verbose_name="Почтовый индекс"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        to="catalog.product", verbose_name="Продукты"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
