# Generated by Django 5.1.7 on 2025-03-27 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_options_remove_order_products_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_created",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
    ]
